name = "omos real survival modpack"
author = "omo50"
version = "1.0.0+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6be523fbb1d31b6d5ee29eb140d16ba8b80d032c56386adae0eca93f9d99afd9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
