name = "omos real survival modpack"
author = "omo50"
version = "1.0.0+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea65c0ab30f97145cfa28da428658b2e5a88078bee0766ef8d724e9124202702"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
